name: main
on:
   workflow_dispatch:
    inputs:
      device:
          description: 'Device'
          default: 'ginkgo'
          required: true
      repo:
          description: 'Kernel source'
          default: 'https://github.com/malkist01/Tobrut'
          required: true
      branch:
          description: 'Kernel source branch'
          default: '16'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7868194496:AAGY7WwRRbeCOPYOnczoCPh2psC43Q0F3JI'
          required: true
      chat_id:
          description: 'Telegram chat id'
          default: '-1002287610863'
          required: true

jobs:
  build:
       runs-on: ubuntu-latest

       steps:
       - name: Creating env!
         uses: actions/checkout@v2

       - name: Setting up env!
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install git make bc bison -y ccache \
              openssl curl zip kmod cpio flex libelf-dev \
              libssl-dev libtfm-dev wget device-tree-compiler \
              ca-certificates python3 python2 binutils \
              binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
       - name: Building Kernel...
         run: |
             chmod +x kernel.sh && bash kernel.sh
             shell: bash
             env:
              TZ: Asia/Jakarta
              REPO: ${{ github.event.inputs.repo }}
              BRANCH: ${{ github.event.inputs.branch }}
              token: ${{ github.event.inputs.token }}
              chat_id: ${{ github.event.inputs.chat_id }}
