name: Kernel Build
env:
      TOKEN: ${{ secrets.BOT_API_KEY }}

on:
  workflow_dispatch:
    inputs:
      repo:
          description: 'Kernel source'
          default: 'https://github.com/malkist01/G1'
          required: true
      branch:
          description: 'Kernel source branch'
          default: 'main'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7868194496:AAGY7WwRRbeCOPYOnczoCPh2psC43Q0F3JI'
          required: true
      chat_id:
          description: 'Telegram chat id'
          default: '-1002287610863'
          required: true


env:
  TZ: Asia/Jakarta
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-24.04

    steps:
      - name: Initializing environment
        run: |
          sudo apt update
          sudo apt install -y \
          bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev \
          openssl python-is-python3 ssh wget zip sudo make clang \
          gcc-arm-linux-gnueabi software-properties-common build-essential \
          libarchive-tools gcc-aarch64-linux-gnu libssl-dev libffi-dev \
          libncurses5-dev zlib1g zlib1g-dev libreadline-dev libbz2-dev \
          libsqlite3-dev make gcc pigz python3 cpio lld

      - name: Build Kernel
        run: bash kernel.sh
